"""
Report Generation Module
Creates PDF and HTML reports from calculation results.
Uses Jinja2 templates for rendering.
"""

import structlog
from typing import Dict, Any, Optional
from pathlib import Path

logger = structlog.get_logger()


class ReportGenerator:
    """
    Generate reports from calculation results.
    Supports HTML and PDF output (WeasyPrint optional).
    """

    TEMPLATE_DIR = Path(__file__).parent.parent / "templates"

    @classmethod
    def generate_html_report(
        cls,
        calculation_type: str,
        results: Dict[str, Any],
        organization_name: str = "Organization",
    ) -> str:
        """
        Generate HTML report from calculation results.

        Args:
            calculation_type: Type of calculation
            results: Calculation output
            organization_name: Name of the organization

        Returns:
            HTML string
        """
        try:
            # Try to use Jinja2 if available
            try:
                from jinja2 import Environment, FileSystemLoader
                env = Environment(loader=FileSystemLoader(str(cls.TEMPLATE_DIR)))

                template_name = f"{calculation_type}.html"
                template = env.get_template(template_name)

                html = template.render(
                    organization_name=organization_name,
                    calculation_type=calculation_type,
                    results=results,
                )

                return html

            except Exception as e:
                logger.warning("jinja2_template_not_found", error=str(e))
                # Fall back to basic HTML
                return cls._generate_basic_html(calculation_type, results, organization_name)

        except Exception as e:
            logger.error("generate_html_report_error", error=str(e))
            raise

    @classmethod
    def _generate_basic_html(
        cls,
        calculation_type: str,
        results: Dict[str, Any],
        organization_name: str,
    ) -> str:
        """Generate a basic HTML report without Jinja2."""
        total_cost = results.get("total_annual_cost", 0)

        html = f"""
        <html>
        <head>
            <meta charset="utf-8">
            <title>ModellenWerk Workforce Report - {calculation_type}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; color: #333; }}
                h1 {{ color: #1e40af; }}
                h2 {{ color: #3b82f6; margin-top: 30px; }}
                .summary {{ background-color: #f0f9ff; padding: 15px; border-radius: 5px; }}
                .breakdown {{ margin-top: 20px; }}
                table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
                th, td {{ text-align: left; padding: 10px; border-bottom: 1px solid #ddd; }}
                th {{ background-color: #f3f4f6; }}
            </style>
        </head>
        <body>
            <h1>ModellenWerk Workforce Analysis Report</h1>
            <h2>Organization: {organization_name}</h2>
            <h3>Calculation Type: {calculation_type.replace('_', ' ').title()}</h3>

            <div class="summary">
                <h3>Key Finding</h3>
                <p><strong>Total Annual Cost: €{total_cost:,.0f}</strong></p>
            </div>

            <div class="breakdown">
                <h2>Breakdown</h2>
                <p>Detailed results are available in the API response.</p>
            </div>

            <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd;">
                <p><em>Generated by ModellenWerk Workforce Intelligence</em></p>
            </div>
        </body>
        </html>
        """

        return html

    @classmethod
    def generate_pdf_report(
        cls,
        calculation_type: str,
        results: Dict[str, Any],
        organization_name: str = "Organization",
    ) -> Optional[bytes]:
        """
        Generate PDF report from calculation results.
        Requires WeasyPrint (optional dependency).

        Args:
            calculation_type: Type of calculation
            results: Calculation output
            organization_name: Name of the organization

        Returns:
            PDF bytes or None if WeasyPrint not available
        """
        try:
            from weasyprint import HTML
            import io

            html_content = cls.generate_html_report(calculation_type, results, organization_name)

            pdf_bytes = io.BytesIO()
            HTML(string=html_content).write_pdf(pdf_bytes)

            return pdf_bytes.getvalue()

        except ImportError:
            logger.warning("weasyprint_not_installed")
            return None
        except Exception as e:
            logger.error("generate_pdf_report_error", error=str(e))
            return None
