"""Seed organization data from the readiness scan 2026 into the database."""

import structlog
from pathlib import Path

from app.core.database import execute, fetch_one, execute_many, get_connection

logger = structlog.get_logger()


# Complete organization data extracted from readiness scan
ORGANIZATIONS_DATA = [
    # ZORG (10 orgs)
    {
        "name": "Leids Universitair Medisch Centrum",
        "sector_slug": "zorg",
        "fte": 7256,
        "personeelskosten_mln": 701.1,
        "omzet_budget_mln": 1180.3,
        "vacatures": 750,
        "verzuim_pct": 5.2,
        "gem_jaarsalaris": 96624,
        "kritieke_functies": "verpleegkundigen, operatieassistenten, onderzoekers",
        "kosten_werving_mln": 32.6,
        "kosten_onvervuld_mln": 80.0,
        "kosten_inhuur_mln": 84.1,
        "kosten_verzuim_mln": 31.0,
        "kosten_burnout_mln": 26.1,
        "kosten_krapte_totaal_mln": 253.9,
        "ai_baten_25_mln": 42.0,
        "ai_baten_50_mln": 84.1,
        "ai_baten_75_mln": 126.1,
        "fte_bespaard_50": 1923,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "AI in radiologie, robotchirurgie voor prostaatkanker, ontwikkeling van uitlegbare AI voor het opsporen van erfelijke cholesterolziekte, en opname van AI in het medisch curriculum.",
    },
    {
        "name": "Erasmus MC",
        "sector_slug": "zorg",
        "fte": 13480,
        "personeelskosten_mln": 1249.0,
        "omzet_budget_mln": 2500.0,
        "vacatures": 142,
        "verzuim_pct": 7.8,
        "gem_jaarsalaris": 92657,
        "kritieke_functies": "verpleegkundigen, operatieassistenten",
        "kosten_werving_mln": 5.9,
        "kosten_onvervuld_mln": 14.5,
        "kosten_inhuur_mln": 21.1,
        "kosten_verzuim_mln": 82.8,
        "kosten_burnout_mln": 48.5,
        "kosten_krapte_totaal_mln": 172.8,
        "ai_baten_25_mln": 75.4,
        "ai_baten_50_mln": 150.8,
        "ai_baten_75_mln": 226.3,
        "fte_bespaard_50": 3572,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "Smart Operating Room 2030: AI voor optimalisatie van OK-planning en onderzoek naar impact nieuwe instrumenten op welzijn OK-personeel.",
    },
    {
        "name": "Universitair Medisch Centrum Groningen",
        "sector_slug": "zorg",
        "fte": 13540,
        "personeelskosten_mln": 1173.7,
        "omzet_budget_mln": 1989.6,
        "vacatures": 76,
        "verzuim_pct": 6.7,
        "gem_jaarsalaris": 86683,
        "kritieke_functies": "verpleegkundigen, operatieassistenten",
        "kosten_werving_mln": 3.0,
        "kosten_onvervuld_mln": 7.3,
        "kosten_inhuur_mln": 10.5,
        "kosten_verzuim_mln": 66.8,
        "kosten_burnout_mln": 48.7,
        "kosten_krapte_totaal_mln": 136.4,
        "ai_baten_25_mln": 70.5,
        "ai_baten_50_mln": 140.9,
        "ai_baten_75_mln": 211.4,
        "fte_bespaard_50": 3588,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "AI-ondersteuning bij beantwoorden van patiëntvragen, AI-fabriek in oprichting, onderzoek naar robotchirurgie.",
    },
    {
        "name": "Amsterdam UMC",
        "sector_slug": "zorg",
        "fte": 17693,
        "personeelskosten_mln": 719.3,
        "omzet_budget_mln": 1210.9,
        "vacatures": 39,
        "verzuim_pct": 7.0,
        "gem_jaarsalaris": 54726,
        "kritieke_functies": "verpleegkundigen, IC-artsen, OK-assistenten, laboranten",
        "kosten_werving_mln": 1.0,
        "kosten_onvervuld_mln": 2.4,
        "kosten_inhuur_mln": 3.4,
        "kosten_verzuim_mln": 57.6,
        "kosten_burnout_mln": 63.7,
        "kosten_krapte_totaal_mln": 128.0,
        "ai_baten_25_mln": 54.7,
        "ai_baten_50_mln": 109.4,
        "ai_baten_75_mln": 164.1,
        "fte_bespaard_50": 4689,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "Amsterdam UMC is actief met AI en robotisering, inclusief de inzet van de Da Vinci operatierobot voor precisiechirurgie en de ontwikkeling van AI-tools voor het analyseren van medische beelden.",
    },
    {
        "name": "UMC Utrecht",
        "sector_slug": "zorg",
        "fte": 12000,
        "personeelskosten_mln": 932.2,
        "omzet_budget_mln": 1684.6,
        "vacatures": 114,
        "verzuim_pct": 5.7,
        "gem_jaarsalaris": 65000,
        "kritieke_functies": "verpleegkundigen, artsen, IT-specialisten",
        "kosten_werving_mln": 3.3,
        "kosten_onvervuld_mln": 8.2,
        "kosten_inhuur_mln": 11.9,
        "kosten_verzuim_mln": 37.8,
        "kosten_burnout_mln": 43.2,
        "kosten_krapte_totaal_mln": 104.4,
        "ai_baten_25_mln": 48.7,
        "ai_baten_50_mln": 97.4,
        "ai_baten_75_mln": 146.1,
        "fte_bespaard_50": 3180,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "UMC Utrecht heeft een datascience-programma en AI Labs om AI te integreren in de dagelijkse gezondheidszorg, onderzoek en onderwijs.",
    },
    {
        "name": "Radboudumc",
        "sector_slug": "zorg",
        "fte": 8293,
        "personeelskosten_mln": 780.5,
        "omzet_budget_mln": 1446.6,
        "vacatures": 91,
        "verzuim_pct": 6.5,
        "gem_jaarsalaris": 75382,
        "kritieke_functies": "verpleegkundigen, onderzoekers, artsen",
        "kosten_werving_mln": 3.1,
        "kosten_onvervuld_mln": 7.6,
        "kosten_inhuur_mln": 11.0,
        "kosten_verzuim_mln": 34.5,
        "kosten_burnout_mln": 29.9,
        "kosten_krapte_totaal_mln": 86.0,
        "ai_baten_25_mln": 39.7,
        "ai_baten_50_mln": 79.3,
        "ai_baten_75_mln": 119.0,
        "fte_bespaard_50": 2198,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "Radboudumc heeft een Technology Center for Artificial Intelligence, gericht op big data-analyse, deep learning en beeldanalyse, en het 'AI for Health'-initiatief.",
    },
    {
        "name": "Isala",
        "sector_slug": "zorg",
        "fte": 7000,
        "personeelskosten_mln": 428.7,
        "omzet_budget_mln": 865.6,
        "vacatures": 56,
        "verzuim_pct": 6.3,
        "gem_jaarsalaris": 61241,
        "kritieke_functies": "verpleegkundigen, operatieassistenten, anesthesiemedewerkers",
        "kosten_werving_mln": 1.5,
        "kosten_onvervuld_mln": 3.8,
        "kosten_inhuur_mln": 5.5,
        "kosten_verzuim_mln": 23.0,
        "kosten_burnout_mln": 25.2,
        "kosten_krapte_totaal_mln": 59.0,
        "ai_baten_25_mln": 25.7,
        "ai_baten_50_mln": 51.4,
        "ai_baten_75_mln": 77.1,
        "fte_bespaard_50": 1855,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "Isala zet AI en RPA in om de zorgadministratie te optimaliseren in samenwerking met ValueCare.",
    },
    {
        "name": "Maastricht UMC+",
        "sector_slug": "zorg",
        "fte": 6762,
        "personeelskosten_mln": 671.2,
        "omzet_budget_mln": 1171.5,
        "vacatures": 57,
        "verzuim_pct": 6.2,
        "gem_jaarsalaris": 54216,
        "kritieke_functies": "verpleegkundigen, artsen, technici",
        "kosten_werving_mln": 1.4,
        "kosten_onvervuld_mln": 3.4,
        "kosten_inhuur_mln": 4.9,
        "kosten_verzuim_mln": 19.3,
        "kosten_burnout_mln": 24.3,
        "kosten_krapte_totaal_mln": 53.4,
        "ai_baten_25_mln": 26.2,
        "ai_baten_50_mln": 52.4,
        "ai_baten_75_mln": 78.5,
        "fte_bespaard_50": 1792,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "Coördineert de uitrol van AI in de Europese gezondheidszorg, heeft een nieuwe precisierobot voor reconstructieve microchirurgie en maakt gebruik van de Da Vinci 5-robot.",
    },
    {
        "name": "Maxima MC",
        "sector_slug": "zorg",
        "fte": 4480,
        "personeelskosten_mln": 176.8,
        "omzet_budget_mln": 410.4,
        "vacatures": 36,
        "verzuim_pct": 5.7,
        "gem_jaarsalaris": 39470,
        "kritieke_functies": "verpleegkundigen, ANIOS IC, CCU verpleegkundige",
        "kosten_werving_mln": 0.6,
        "kosten_onvervuld_mln": 1.6,
        "kosten_inhuur_mln": 2.3,
        "kosten_verzuim_mln": 8.6,
        "kosten_burnout_mln": 16.1,
        "kosten_krapte_totaal_mln": 29.2,
        "ai_baten_25_mln": 10.6,
        "ai_baten_50_mln": 21.1,
        "ai_baten_75_mln": 31.7,
        "fte_bespaard_50": 1187,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "Maxima MC maakt gebruik van een operatierobot, een medicijnrobot en een robotarm. Ze doen onderzoek naar AI voor hartdiagnoses en een 'slim matras'.",
    },
    {
        "name": "Catharina Ziekenhuis",
        "sector_slug": "zorg",
        "fte": 3026,
        "personeelskosten_mln": 245.8,
        "omzet_budget_mln": 590.7,
        "vacatures": 46,
        "verzuim_pct": 6.0,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "verpleegkundigen, IC-artsen, OK-assistenten",
        "kosten_werving_mln": 1.1,
        "kosten_onvervuld_mln": 2.8,
        "kosten_inhuur_mln": 4.0,
        "kosten_verzuim_mln": 8.5,
        "kosten_burnout_mln": 10.9,
        "kosten_krapte_totaal_mln": 27.4,
        "ai_baten_25_mln": 11.1,
        "ai_baten_50_mln": 22.1,
        "ai_baten_75_mln": 33.2,
        "fte_bespaard_50": 802,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_status": "Het ziekenhuis gebruikt de Da Vinci Xi robot voor operaties en heeft een AI Expertisecentrum. Initiatieven omvatten AI-ondersteunde IC-zorg, het voorspellen van complicaties bij hartpatiënten.",
    },
    # ENERGIE (10 orgs)
    {
        "name": "Alliander",
        "sector_slug": "energie",
        "fte": 9400,
        "personeelskosten_mln": 997.0,
        "omzet_budget_mln": 3043.0,
        "vacatures": 242,
        "verzuim_pct": 4.1,
        "gem_jaarsalaris": 106063,
        "kritieke_functies": "technici, IT-specialisten",
        "kosten_werving_mln": 12.8,
        "kosten_onvervuld_mln": 31.5,
        "kosten_inhuur_mln": 41.1,
        "kosten_verzuim_mln": 13.9,
        "kosten_burnout_mln": 27.1,
        "kosten_krapte_totaal_mln": 126.4,
        "ai_baten_25_mln": 66.0,
        "ai_baten_50_mln": 132.0,
        "ai_baten_75_mln": 198.0,
        "fte_bespaard_50": 2820,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Alliander is actief met AI en robotica, inclusief een AI-position paper, een samenwerking met AWS voor generatieve AI, een robotica-lab en de inzet van Spot-robots.",
    },
    {
        "name": "Shell Nederland",
        "sector_slug": "energie",
        "fte": 8421,
        "personeelskosten_mln": 631.6,
        "omzet_budget_mln": 355500.0,
        "vacatures": 293,
        "verzuim_pct": 6.4,
        "gem_jaarsalaris": 76000,
        "kritieke_functies": "engineers, operators, maintenance technicians, IT-specialisten, data scientists",
        "kosten_werving_mln": 11.1,
        "kosten_onvervuld_mln": 27.3,
        "kosten_inhuur_mln": 35.6,
        "kosten_verzuim_mln": 13.9,
        "kosten_burnout_mln": 24.3,
        "kosten_krapte_totaal_mln": 112.3,
        "ai_baten_25_mln": 42.7,
        "ai_baten_50_mln": 85.4,
        "ai_baten_75_mln": 128.0,
        "fte_bespaard_50": 2526,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Shell investeert in AI voor o.a. het voorkomen van storingen en het vinden van nieuwe olie- en gasbronnen. In Pernis worden robots en drones ingezet voor inspecties, zoals de 'CatSpider'.",
    },
    {
        "name": "Enexis",
        "sector_slug": "energie",
        "fte": 5981,
        "personeelskosten_mln": 741.0,
        "omzet_budget_mln": 2596.0,
        "vacatures": 211,
        "verzuim_pct": 5.0,
        "gem_jaarsalaris": 56706,
        "kritieke_functies": "Technische medewerkers, elektrotechniek",
        "kosten_werving_mln": 6.0,
        "kosten_onvervuld_mln": 14.7,
        "kosten_inhuur_mln": 19.1,
        "kosten_verzuim_mln": 5.8,
        "kosten_burnout_mln": 17.2,
        "kosten_krapte_totaal_mln": 62.8,
        "ai_baten_25_mln": 29.9,
        "ai_baten_50_mln": 59.8,
        "ai_baten_75_mln": 89.7,
        "fte_bespaard_50": 1794,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Enexis gebruikt machine learning om de impact van elektrische voertuigen op het elektriciteitsnet te voorspellen en voor het detecteren van onveilige situaties.",
    },
    {
        "name": "Stedin",
        "sector_slug": "energie",
        "fte": 5471,
        "personeelskosten_mln": 199.0,
        "omzet_budget_mln": 2100.0,
        "vacatures": 122,
        "verzuim_pct": 5.0,
        "gem_jaarsalaris": 59250,
        "kritieke_functies": "technisch personeel, monteurs, engineers, IT-specialisten",
        "kosten_werving_mln": 3.6,
        "kosten_onvervuld_mln": 8.9,
        "kosten_inhuur_mln": 11.6,
        "kosten_verzuim_mln": 5.5,
        "kosten_burnout_mln": 15.8,
        "kosten_krapte_totaal_mln": 45.3,
        "ai_baten_25_mln": 19.2,
        "ai_baten_50_mln": 38.5,
        "ai_baten_75_mln": 57.7,
        "fte_bespaard_50": 1641,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Stedin gebruikt AI voor het optimaliseren van het elektriciteitsnet, intelligente automatisering en het ontwerpen van netten voor nieuwe woonwijken.",
    },
    {
        "name": "TenneT",
        "sector_slug": "energie",
        "fte": 8483,
        "personeelskosten_mln": 353.0,
        "omzet_budget_mln": 9999.0,
        "vacatures": 47,
        "verzuim_pct": 3.6,
        "gem_jaarsalaris": 75000,
        "kritieke_functies": "engineers, projectmanagers, IT-specialisten, technici, data-analisten",
        "kosten_werving_mln": 1.8,
        "kosten_onvervuld_mln": 4.3,
        "kosten_inhuur_mln": 5.6,
        "kosten_verzuim_mln": 7.8,
        "kosten_burnout_mln": 24.4,
        "kosten_krapte_totaal_mln": 43.9,
        "ai_baten_25_mln": 36.9,
        "ai_baten_50_mln": 73.7,
        "ai_baten_75_mln": 110.6,
        "fte_bespaard_50": 2545,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Gebruikt AI en automatisering voor netwerkstabilisatie en -onderhoud, inclusief autonome robots met akoestische camera's voor het detecteren van storingen.",
    },
    {
        "name": "Gasunie",
        "sector_slug": "energie",
        "fte": 2793,
        "personeelskosten_mln": 281.0,
        "omzet_budget_mln": 1955.0,
        "vacatures": 75,
        "verzuim_pct": 4.1,
        "gem_jaarsalaris": 74502,
        "kritieke_functies": "Engineering, stakeholder management",
        "kosten_werving_mln": 2.8,
        "kosten_onvervuld_mln": 6.9,
        "kosten_inhuur_mln": 8.9,
        "kosten_verzuim_mln": 2.9,
        "kosten_burnout_mln": 8.0,
        "kosten_krapte_totaal_mln": 29.5,
        "ai_baten_25_mln": 15.1,
        "ai_baten_50_mln": 30.2,
        "ai_baten_75_mln": 45.3,
        "fte_bespaard_50": 838,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Pilot with exoskeletons, AI/ML for CO2 prediction and heat demand forecasting, Digital Twin for heating network.",
    },
    {
        "name": "Eneco",
        "sector_slug": "energie",
        "fte": 3780,
        "personeelskosten_mln": 389.0,
        "omzet_budget_mln": 7239.0,
        "vacatures": 67,
        "verzuim_pct": 4.5,
        "gem_jaarsalaris": 57207,
        "kritieke_functies": "Data Engineers, Big Data Engineers, Quantitative Analysts, IT-specialisten",
        "kosten_werving_mln": 1.9,
        "kosten_onvervuld_mln": 4.7,
        "kosten_inhuur_mln": 6.1,
        "kosten_verzuim_mln": 3.3,
        "kosten_burnout_mln": 10.9,
        "kosten_krapte_totaal_mln": 26.9,
        "ai_baten_25_mln": 17.5,
        "ai_baten_50_mln": 34.9,
        "ai_baten_75_mln": 52.4,
        "fte_bespaard_50": 1134,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Eneco gebruikt AI voor klantenservice (chatbots, voice agents), energiehandel (real-time voorspellingen) en is bezig met Robotic Process Automation (RPA).",
    },
    {
        "name": "Vattenfall Nederland",
        "sector_slug": "energie",
        "fte": 4100,
        "personeelskosten_mln": 401.0,
        "omzet_budget_mln": 4980.0,
        "vacatures": 24,
        "verzuim_pct": 5.7,
        "gem_jaarsalaris": 80000,
        "kritieke_functies": "Technici, (service)monteurs, engineers, IT-specialisten",
        "kosten_werving_mln": 1.0,
        "kosten_onvervuld_mln": 2.4,
        "kosten_inhuur_mln": 3.1,
        "kosten_verzuim_mln": 6.4,
        "kosten_burnout_mln": 11.8,
        "kosten_krapte_totaal_mln": 24.6,
        "ai_baten_25_mln": 23.2,
        "ai_baten_50_mln": 46.4,
        "ai_baten_75_mln": 69.5,
        "fte_bespaard_50": 1230,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Vattenfall gebruikt AI voor data-analyse, het optimaliseren van energieopwekking en -handel, en het voorspellen van onderhoud. Robot-hond Spot wordt ingezet voor inspecties.",
    },
    {
        "name": "Essent",
        "sector_slug": "energie",
        "fte": 2870,
        "personeelskosten_mln": 172.2,
        "omzet_budget_mln": 192.0,
        "vacatures": 19,
        "verzuim_pct": 5.5,
        "gem_jaarsalaris": 60000,
        "kritieke_functies": "Procurement, Project & Product Management, Legal & Compliance, Sales, Data, Digital, Strategy, IT, Finance",
        "kosten_werving_mln": 0.6,
        "kosten_onvervuld_mln": 1.4,
        "kosten_inhuur_mln": 1.8,
        "kosten_verzuim_mln": 3.2,
        "kosten_burnout_mln": 8.3,
        "kosten_krapte_totaal_mln": 15.3,
        "ai_baten_25_mln": 11.4,
        "ai_baten_50_mln": 22.9,
        "ai_baten_75_mln": 34.3,
        "fte_bespaard_50": 861,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "Essent heeft 'Bolt' ontwikkeld, een AI-gestuurde agent-assist bot, en maakt gebruik van Robotic Process Automation (RPA).",
    },
    {
        "name": "RWE Nederland",
        "sector_slug": "energie",
        "fte": 850,
        "personeelskosten_mln": 75.0,
        "omzet_budget_mln": 1500.0,
        "vacatures": 17,
        "verzuim_pct": 4.5,
        "gem_jaarsalaris": 65000,
        "kritieke_functies": "HR-adviseurs, Operationeel Managers, Technisch specialisten",
        "kosten_werving_mln": 0.6,
        "kosten_onvervuld_mln": 1.4,
        "kosten_inhuur_mln": 1.8,
        "kosten_verzuim_mln": 0.8,
        "kosten_burnout_mln": 2.4,
        "kosten_krapte_totaal_mln": 7.0,
        "ai_baten_25_mln": 4.0,
        "ai_baten_50_mln": 8.0,
        "ai_baten_75_mln": 12.1,
        "fte_bespaard_50": 255,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_status": "RWE investeert in digitalisering en data-analyse voor het optimaliseren van energieproductie en -handel.",
    },
    # OVERHEID (10 orgs)
    {
        "name": "Nationale Politie",
        "sector_slug": "overheid",
        "fte": 65549,
        "personeelskosten_mln": 5982.5,
        "omzet_budget_mln": 8151.3,
        "vacatures": 1300,
        "verzuim_pct": 6.3,
        "gem_jaarsalaris": 84000,
        "kritieke_functies": "zedenteams, recherche, IT-specialisten, cybercrime-experts",
        "kosten_werving_mln": 41.0,
        "kosten_onvervuld_mln": 100.5,
        "kosten_inhuur_mln": 174.7,
        "kosten_verzuim_mln": 176.9,
        "kosten_burnout_mln": 204.5,
        "kosten_krapte_totaal_mln": 697.6,
        "ai_baten_25_mln": 454.5,
        "ai_baten_50_mln": 909.0,
        "ai_baten_75_mln": 1363.5,
        "fte_bespaard_50": 21959,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "De politie heeft in 2024 de inventarisatie en registratie van alle AI-systemen en algoritmes afgerond. Er wordt ook gewerkt aan de inzet van AI bij cold cases.",
    },
    {
        "name": "Ministerie van Justitie en Veiligheid",
        "sector_slug": "overheid",
        "fte": 52236,
        "personeelskosten_mln": 4350.0,
        "omzet_budget_mln": 22966.5,
        "vacatures": 1500,
        "verzuim_pct": 6.2,
        "gem_jaarsalaris": 75000,
        "kritieke_functies": "IT-specialisten, juristen, beleidsmedewerkers, gevangenispersoneel",
        "kosten_werving_mln": 42.2,
        "kosten_onvervuld_mln": 103.6,
        "kosten_inhuur_mln": 180.0,
        "kosten_verzuim_mln": 123.9,
        "kosten_burnout_mln": 163.0,
        "kosten_krapte_totaal_mln": 612.6,
        "ai_baten_25_mln": 324.9,
        "ai_baten_50_mln": 649.8,
        "ai_baten_75_mln": 974.8,
        "fte_bespaard_50": 17499,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "Het ministerie experimenteert met AI voor het analyseren van grote hoeveelheden documenten en het detecteren van ondermijnende criminaliteit.",
    },
    {
        "name": "Ministerie van Defensie",
        "sector_slug": "overheid",
        "fte": 79323,
        "personeelskosten_mln": 6916.8,
        "omzet_budget_mln": 22019.6,
        "vacatures": 620,
        "verzuim_pct": 6.4,
        "gem_jaarsalaris": 66329,
        "kritieke_functies": "ICT-personeel, technici, (lucht)gevechtsleiding, logistiek personeel",
        "kosten_werving_mln": 15.4,
        "kosten_onvervuld_mln": 37.9,
        "kosten_inhuur_mln": 65.8,
        "kosten_verzuim_mln": 171.7,
        "kosten_burnout_mln": 247.5,
        "kosten_krapte_totaal_mln": 538.3,
        "ai_baten_25_mln": 452.1,
        "ai_baten_50_mln": 904.3,
        "ai_baten_75_mln": 1356.4,
        "fte_bespaard_50": 26573,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "Defensie zet in op innovaties zoals drones, AI-toepassingen en robotica. AI wordt gezien als een cruciale factor voor militaire operaties.",
    },
    {
        "name": "DJI Dienst Justitiële Inrichtingen",
        "sector_slug": "overheid",
        "fte": 16000,
        "personeelskosten_mln": 1418.7,
        "omzet_budget_mln": 3348.1,
        "vacatures": 2958,
        "verzuim_pct": 6.0,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "psychiaters, beveiligingspersoneel",
        "kosten_werving_mln": 61.0,
        "kosten_onvervuld_mln": 149.7,
        "kosten_inhuur_mln": 105.6,
        "kosten_verzuim_mln": 26.9,
        "kosten_burnout_mln": 49.9,
        "kosten_krapte_totaal_mln": 393.2,
        "ai_baten_25_mln": 80.6,
        "ai_baten_50_mln": 161.2,
        "ai_baten_75_mln": 241.7,
        "fte_bespaard_50": 5360,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "DJI experimenteert met een robothond voor celinspecties en zet RPA in voor de verbetering van de dienstverlening.",
    },
    {
        "name": "Belastingdienst",
        "sector_slug": "overheid",
        "fte": 28500,
        "personeelskosten_mln": 1852.5,
        "omzet_budget_mln": 2500.0,
        "vacatures": 112,
        "verzuim_pct": 5.3,
        "gem_jaarsalaris": 65000,
        "kritieke_functies": "ICT, Fiscaal & juridisch, Data & analyse, Accountancy & finance",
        "kosten_werving_mln": 2.7,
        "kosten_onvervuld_mln": 6.7,
        "kosten_inhuur_mln": 11.6,
        "kosten_verzuim_mln": 50.1,
        "kosten_burnout_mln": 88.9,
        "kosten_krapte_totaal_mln": 160.1,
        "ai_baten_25_mln": 149.7,
        "ai_baten_50_mln": 299.4,
        "ai_baten_75_mln": 449.2,
        "fte_bespaard_50": 9548,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "Modernisering van ICT-systemen en automatisering van processen om personeelstekorten op te vangen.",
    },
    {
        "name": "Gemeente Amsterdam",
        "sector_slug": "overheid",
        "fte": 22000,
        "personeelskosten_mln": 2000.0,
        "omzet_budget_mln": 7100.0,
        "vacatures": 83,
        "verzuim_pct": 9.7,
        "gem_jaarsalaris": 55470,
        "kritieke_functies": "ICT-specialisten, juristen, handhavers, ingenieurs",
        "kosten_werving_mln": 1.7,
        "kosten_onvervuld_mln": 4.2,
        "kosten_inhuur_mln": 7.4,
        "kosten_verzuim_mln": 60.4,
        "kosten_burnout_mln": 68.6,
        "kosten_krapte_totaal_mln": 142.3,
        "ai_baten_25_mln": 112.8,
        "ai_baten_50_mln": 225.6,
        "ai_baten_75_mln": 338.4,
        "fte_bespaard_50": 7370,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "De gemeente Amsterdam zet AI in om problemen in de stad aan te pakken, de dienstverlening aan bewoners te verbeteren en het werk binnen de organisatie te verbeteren.",
    },
    {
        "name": "UWV",
        "sector_slug": "overheid",
        "fte": 19616,
        "personeelskosten_mln": 2164.0,
        "omzet_budget_mln": 2611.0,
        "vacatures": 105,
        "verzuim_pct": 6.7,
        "gem_jaarsalaris": 54934,
        "kritieke_functies": "Arbeidsdeskundigen, artsen, IT-specialisten",
        "kosten_werving_mln": 2.2,
        "kosten_onvervuld_mln": 5.3,
        "kosten_inhuur_mln": 9.2,
        "kosten_verzuim_mln": 36.8,
        "kosten_burnout_mln": 61.2,
        "kosten_krapte_totaal_mln": 114.7,
        "ai_baten_25_mln": 104.1,
        "ai_baten_50_mln": 208.2,
        "ai_baten_75_mln": 312.2,
        "fte_bespaard_50": 6571,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "UWV zet AI in als hulpmiddel voor professionals, voor automatisering van taken en empowerment van cliënten. Er is een proef met de Groen-app.",
    },
    {
        "name": "Gemeente Rotterdam",
        "sector_slug": "overheid",
        "fte": 14000,
        "personeelskosten_mln": 910.0,
        "omzet_budget_mln": 4700.0,
        "vacatures": 148,
        "verzuim_pct": 7.7,
        "gem_jaarsalaris": 65000,
        "kritieke_functies": "IT/Data, Techniek/Bouwkunde, Zorg/Welzijn/Jeugd",
        "kosten_werving_mln": 3.6,
        "kosten_onvervuld_mln": 8.9,
        "kosten_inhuur_mln": 15.4,
        "kosten_verzuim_mln": 35.7,
        "kosten_burnout_mln": 43.7,
        "kosten_krapte_totaal_mln": 107.3,
        "ai_baten_25_mln": 74.2,
        "ai_baten_50_mln": 148.5,
        "ai_baten_75_mln": 222.7,
        "fte_bespaard_50": 4690,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "Sociaal AI Lab, RPA, verkenning impact robots op economie",
    },
    {
        "name": "Gemeente Den Haag",
        "sector_slug": "overheid",
        "fte": 12000,
        "personeelskosten_mln": 648.8,
        "omzet_budget_mln": 3000.0,
        "vacatures": 94,
        "verzuim_pct": 7.1,
        "gem_jaarsalaris": 54066,
        "kritieke_functies": "IT/Data, Beleid, Bedrijfsvoering & Ondersteuning, Gebieds/Ruimtelijke Ontwikkeling",
        "kosten_werving_mln": 1.9,
        "kosten_onvervuld_mln": 4.7,
        "kosten_inhuur_mln": 8.1,
        "kosten_verzuim_mln": 23.5,
        "kosten_burnout_mln": 37.4,
        "kosten_krapte_totaal_mln": 75.6,
        "ai_baten_25_mln": 52.8,
        "ai_baten_50_mln": 105.6,
        "ai_baten_75_mln": 158.4,
        "fte_bespaard_50": 4020,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "De gemeente heeft een AI-beleid 'AI voor mens en stad' en investeert in kennisopbouw en experimenten met AI-toepassingen.",
    },
    {
        "name": "Rijkswaterstaat",
        "sector_slug": "overheid",
        "fte": 9400,
        "personeelskosten_mln": 1126.9,
        "omzet_budget_mln": 3607.1,
        "vacatures": 41,
        "verzuim_pct": 4.1,
        "gem_jaarsalaris": 65000,
        "kritieke_functies": "Technisch adviseurs, contractmanagers, projectmanagers, assetmanagers",
        "kosten_werving_mln": 1.0,
        "kosten_onvervuld_mln": 2.5,
        "kosten_inhuur_mln": 4.3,
        "kosten_verzuim_mln": 12.8,
        "kosten_burnout_mln": 29.3,
        "kosten_krapte_totaal_mln": 49.8,
        "ai_baten_25_mln": 56.6,
        "ai_baten_50_mln": 113.2,
        "ai_baten_75_mln": 169.8,
        "fte_bespaard_50": 3149,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_status": "Rijkswaterstaat gebruikt drones en AI voor bruginspecties en is betrokken bij de ontwikkeling van een AI-chatbot voor rijksambtenaren.",
    },
    # BOUW (10 orgs)
    {
        "name": "VolkerWessels",
        "sector_slug": "bouw",
        "fte": 13000,
        "personeelskosten_mln": 975.0,
        "omzet_budget_mln": 6000.0,
        "vacatures": 519,
        "verzuim_pct": 5.5,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "timmerlieden, engineers, werkvoorbereiders, projectleiders, uitvoerders",
        "kosten_werving_mln": 15.7,
        "kosten_onvervuld_mln": 38.5,
        "kosten_inhuur_mln": 45.7,
        "kosten_verzuim_mln": 26.7,
        "kosten_burnout_mln": 43.7,
        "kosten_krapte_totaal_mln": 170.3,
        "ai_baten_25_mln": 44.4,
        "ai_baten_50_mln": 88.7,
        "ai_baten_75_mln": 133.1,
        "fte_bespaard_50": 3250,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Investeert in AI voor o.a. parkeeranalyse (Parquery) en zet in op robotisering, chatbots en robotic process automation (RPA).",
    },
    {
        "name": "TBI Holdings",
        "sector_slug": "bouw",
        "fte": 6547,
        "personeelskosten_mln": 735.6,
        "omzet_budget_mln": 2627.0,
        "vacatures": 614,
        "verzuim_pct": 5.5,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "technisch personeel, projectleiders, ingenieurs, vakmensen",
        "kosten_werving_mln": 18.6,
        "kosten_onvervuld_mln": 45.6,
        "kosten_inhuur_mln": 43.2,
        "kosten_verzuim_mln": 13.5,
        "kosten_burnout_mln": 22.0,
        "kosten_krapte_totaal_mln": 142.8,
        "ai_baten_25_mln": 26.1,
        "ai_baten_50_mln": 52.1,
        "ai_baten_75_mln": 78.2,
        "fte_bespaard_50": 1637,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "TBI zet in op digitalisering en kunstmatige intelligentie, onder andere via een 'Digital University' en de entiteit Zebra.",
    },
    {
        "name": "Heijmans",
        "sector_slug": "bouw",
        "fte": 5650,
        "personeelskosten_mln": 439.4,
        "omzet_budget_mln": 2600.0,
        "vacatures": 336,
        "verzuim_pct": 4.8,
        "gem_jaarsalaris": 77770,
        "kritieke_functies": "Onderhoudsmonteurs, loodgieters, elektriciens, werkvoorbereiders, calculators, ingenieurs",
        "kosten_werving_mln": 14.4,
        "kosten_onvervuld_mln": 35.3,
        "kosten_inhuur_mln": 41.8,
        "kosten_verzuim_mln": 14.3,
        "kosten_burnout_mln": 19.0,
        "kosten_krapte_totaal_mln": 124.8,
        "ai_baten_25_mln": 24.8,
        "ai_baten_50_mln": 49.7,
        "ai_baten_75_mln": 74.5,
        "fte_bespaard_50": 1412,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Heijmans zet in op digitalisering en AI met o.a. de BioBuddy voor biodiversiteitsmeting, DORA (een virtuele expert) en datagedreven assetmanagement.",
    },
    {
        "name": "BAM Groep",
        "sector_slug": "bouw",
        "fte": 13172,
        "personeelskosten_mln": 975.5,
        "omzet_budget_mln": 6455.0,
        "vacatures": 250,
        "verzuim_pct": 5.8,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "Werkvoorbereiders, calculators, projectleiders, uitvoerders, BIM-modelleurs",
        "kosten_werving_mln": 7.6,
        "kosten_onvervuld_mln": 18.6,
        "kosten_inhuur_mln": 22.0,
        "kosten_verzuim_mln": 28.6,
        "kosten_burnout_mln": 44.3,
        "kosten_krapte_totaal_mln": 121.0,
        "ai_baten_25_mln": 44.8,
        "ai_baten_50_mln": 89.6,
        "ai_baten_75_mln": 134.3,
        "fte_bespaard_50": 3293,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "BAM maakt gebruik van digitale bouwtechnologieën zoals BIM en onderzoekt de inzet van 3D-betonprinten en robotica.",
    },
    {
        "name": "Dura Vermeer",
        "sector_slug": "bouw",
        "fte": 3329,
        "personeelskosten_mln": 216.4,
        "omzet_budget_mln": 2076.0,
        "vacatures": 358,
        "verzuim_pct": 4.1,
        "gem_jaarsalaris": 50000,
        "kritieke_functies": "Technisch geschoolde vakmensen",
        "kosten_werving_mln": 9.8,
        "kosten_onvervuld_mln": 24.2,
        "kosten_inhuur_mln": 20.0,
        "kosten_verzuim_mln": 4.6,
        "kosten_burnout_mln": 11.2,
        "kosten_krapte_totaal_mln": 69.8,
        "ai_baten_25_mln": 10.1,
        "ai_baten_50_mln": 20.3,
        "ai_baten_75_mln": 30.4,
        "fte_bespaard_50": 832,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Virtual Factory voor industriële woningbouwmodules, circulair woningconcept Aer.",
    },
    {
        "name": "Boskalis",
        "sector_slug": "bouw",
        "fte": 7806,
        "personeelskosten_mln": 402.1,
        "omzet_budget_mln": 4362.0,
        "vacatures": 127,
        "verzuim_pct": 4.8,
        "gem_jaarsalaris": 51500,
        "kritieke_functies": "Engineers, Project Managers, Superintendents",
        "kosten_werving_mln": 3.6,
        "kosten_onvervuld_mln": 8.8,
        "kosten_inhuur_mln": 10.5,
        "kosten_verzuim_mln": 13.1,
        "kosten_burnout_mln": 26.2,
        "kosten_krapte_totaal_mln": 62.2,
        "ai_baten_25_mln": 22.6,
        "ai_baten_50_mln": 45.3,
        "ai_baten_75_mln": 67.9,
        "fte_bespaard_50": 1952,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Dedicated Artificial Intelligence program to boost competitive strength and productivity.",
    },
    {
        "name": "Van Oord",
        "sector_slug": "bouw",
        "fte": 5766,
        "personeelskosten_mln": 859.8,
        "omzet_budget_mln": 2866.0,
        "vacatures": 150,
        "verzuim_pct": 4.7,
        "gem_jaarsalaris": 54000,
        "kritieke_functies": "Gespecialiseerde technische functies zoals (offshore) engineers, projectmanagers en maritiem personeel.",
        "kosten_werving_mln": 4.5,
        "kosten_onvervuld_mln": 10.9,
        "kosten_inhuur_mln": 13.0,
        "kosten_verzuim_mln": 10.0,
        "kosten_burnout_mln": 19.4,
        "kosten_krapte_totaal_mln": 57.7,
        "ai_baten_25_mln": 25.6,
        "ai_baten_50_mln": 51.1,
        "ai_baten_75_mln": 76.7,
        "fte_bespaard_50": 1442,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Data en digitalisering zijn de sleutel tot het bereiken van operationele excellentie en het ontwikkelen van nieuwe bedrijfsmodellen.",
    },
    {
        "name": "Strukton Groep B.V.",
        "sector_slug": "bouw",
        "fte": 4000,
        "personeelskosten_mln": 380.5,
        "omzet_budget_mln": 1601.7,
        "vacatures": 150,
        "verzuim_pct": 9.0,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "technische specialisten, monteurs, projectleiders, ingenieurs",
        "kosten_werving_mln": 4.5,
        "kosten_onvervuld_mln": 11.1,
        "kosten_inhuur_mln": 13.2,
        "kosten_verzuim_mln": 13.5,
        "kosten_burnout_mln": 13.4,
        "kosten_krapte_totaal_mln": 55.8,
        "ai_baten_25_mln": 15.2,
        "ai_baten_50_mln": 30.5,
        "ai_baten_75_mln": 45.7,
        "fte_bespaard_50": 1000,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Gebruik van elektrische railkranen, onderzoek naar elektrische bestelwagens, focus op datagedreven asset management.",
    },
    {
        "name": "Ballast Nedam",
        "sector_slug": "bouw",
        "fte": 3166,
        "personeelskosten_mln": 295.9,
        "omzet_budget_mln": 1232.6,
        "vacatures": 125,
        "verzuim_pct": 4.8,
        "gem_jaarsalaris": 47922,
        "kritieke_functies": "calculator, werkvoorbereider, uitvoerder, projectleider",
        "kosten_werving_mln": 3.3,
        "kosten_onvervuld_mln": 8.1,
        "kosten_inhuur_mln": 9.6,
        "kosten_verzuim_mln": 5.0,
        "kosten_burnout_mln": 10.6,
        "kosten_krapte_totaal_mln": 36.6,
        "ai_baten_25_mln": 10.7,
        "ai_baten_50_mln": 21.3,
        "ai_baten_75_mln": 32.0,
        "fte_bespaard_50": 792,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Ballast Nedam zet een metselrobot in en investeert in digitalisering, waaronder BIM, machine learning en AI.",
    },
    {
        "name": "Van Wijnen Groep",
        "sector_slug": "bouw",
        "fte": 2374,
        "personeelskosten_mln": 190.9,
        "omzet_budget_mln": 1468.0,
        "vacatures": 54,
        "verzuim_pct": 4.8,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "Timmerman, Uitvoerder, Werkvoorbereider, Calculator, Veiligheidskundige",
        "kosten_werving_mln": 1.6,
        "kosten_onvervuld_mln": 4.0,
        "kosten_inhuur_mln": 4.8,
        "kosten_verzuim_mln": 4.3,
        "kosten_burnout_mln": 8.0,
        "kosten_krapte_totaal_mln": 22.6,
        "ai_baten_25_mln": 8.2,
        "ai_baten_50_mln": 16.5,
        "ai_baten_75_mln": 24.7,
        "fte_bespaard_50": 594,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_status": "Van Wijnen heeft een 'woningfabriek' waar robots worden ingezet om de woningbouw te versnellen. Ze nemen ook deel aan het InCUBE-onderzoeksproject.",
    },
    # TRANSPORT (10 orgs)
    {
        "name": "KLM Royal Dutch Airlines",
        "sector_slug": "transport",
        "fte": 33007,
        "personeelskosten_mln": 3954.0,
        "omzet_budget_mln": 12681.0,
        "vacatures": 58,
        "verzuim_pct": 7.6,
        "gem_jaarsalaris": 65000,
        "kritieke_functies": "piloten, onderhoudspersoneel, technici",
        "kosten_werving_mln": 1.8,
        "kosten_onvervuld_mln": 4.4,
        "kosten_inhuur_mln": 6.0,
        "kosten_verzuim_mln": 83.2,
        "kosten_burnout_mln": 103.0,
        "kosten_krapte_totaal_mln": 198.4,
        "ai_baten_25_mln": 201.4,
        "ai_baten_50_mln": 402.8,
        "ai_baten_75_mln": 604.2,
        "fte_bespaard_50": 10232,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "KLM zet AI in om voedselverspilling tegen te gaan, voor slimmere onderhoudsplanning (LiMiTS), en heeft de conversatie-AI-assistent BlueBot.",
    },
    {
        "name": "NS Nederlandse Spoorwegen",
        "sector_slug": "transport",
        "fte": 20800,
        "personeelskosten_mln": 1765.0,
        "omzet_budget_mln": 3702.0,
        "vacatures": 196,
        "verzuim_pct": 7.5,
        "gem_jaarsalaris": 84855,
        "kritieke_functies": "machinisten, conducteurs, monteurs, IT-specialisten",
        "kosten_werving_mln": 7.9,
        "kosten_onvervuld_mln": 19.4,
        "kosten_inhuur_mln": 26.6,
        "kosten_verzuim_mln": 67.5,
        "kosten_burnout_mln": 64.9,
        "kosten_krapte_totaal_mln": 186.3,
        "ai_baten_25_mln": 140.1,
        "ai_baten_50_mln": 280.1,
        "ai_baten_75_mln": 420.2,
        "fte_bespaard_50": 6448,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "NS uses AI for the seat-finder in the NS app and sensors in trains for maintenance prediction. They participate in the ROBUST program and co-founded Kickstart AI.",
    },
    {
        "name": "Arriva Nederland",
        "sector_slug": "transport",
        "fte": 4780,
        "personeelskosten_mln": 215.1,
        "omzet_budget_mln": 804.0,
        "vacatures": 250,
        "verzuim_pct": 9.5,
        "gem_jaarsalaris": 45000,
        "kritieke_functies": "buschauffeurs, machinisten, monteurs",
        "kosten_werving_mln": 5.3,
        "kosten_onvervuld_mln": 13.1,
        "kosten_inhuur_mln": 18.0,
        "kosten_verzuim_mln": 10.4,
        "kosten_burnout_mln": 14.9,
        "kosten_krapte_totaal_mln": 61.8,
        "ai_baten_25_mln": 17.3,
        "ai_baten_50_mln": 34.6,
        "ai_baten_75_mln": 51.9,
        "fte_bespaard_50": 1482,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "Arriva Academy biedt AI-cursussen aan. Samenwerking met TU Delft voor een CO2-barometer. Inzet van digitale hulpmiddelen voor reizigers.",
    },
    {
        "name": "Schiphol Group",
        "sector_slug": "transport",
        "fte": 3527,
        "personeelskosten_mln": 356.8,
        "omzet_budget_mln": 2245.0,
        "vacatures": 300,
        "verzuim_pct": 6.1,
        "gem_jaarsalaris": 45000,
        "kritieke_functies": "bagageafhandelaars, beveiligers, grondpersoneel, technisch personeel",
        "kosten_werving_mln": 6.4,
        "kosten_onvervuld_mln": 15.7,
        "kosten_inhuur_mln": 19.0,
        "kosten_verzuim_mln": 4.9,
        "kosten_burnout_mln": 11.0,
        "kosten_krapte_totaal_mln": 57.1,
        "ai_baten_25_mln": 16.0,
        "ai_baten_50_mln": 32.0,
        "ai_baten_75_mln": 48.0,
        "fte_bespaard_50": 1093,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "Schiphol Group is using an in-house large language model for AI-powered customer care and is testing self-driving wheelchairs.",
    },
    {
        "name": "ProRail",
        "sector_slug": "transport",
        "fte": 5392,
        "personeelskosten_mln": 734.0,
        "omzet_budget_mln": 1890.0,
        "vacatures": 120,
        "verzuim_pct": 4.8,
        "gem_jaarsalaris": 62652,
        "kritieke_functies": "treinverkeersleiders, bedrijfsvoerders, technisch personeel",
        "kosten_werving_mln": 3.6,
        "kosten_onvervuld_mln": 8.8,
        "kosten_inhuur_mln": 12.0,
        "kosten_verzuim_mln": 8.3,
        "kosten_burnout_mln": 16.8,
        "kosten_krapte_totaal_mln": 49.5,
        "ai_baten_25_mln": 33.1,
        "ai_baten_50_mln": 66.2,
        "ai_baten_75_mln": 99.3,
        "fte_bespaard_50": 1672,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "ProRail experimenteert met AI-gebaseerde Rail OCR, heeft een Datalab, ontwikkelt een LLM-aangedreven chatbot en onderzoekt robotica.",
    },
    {
        "name": "Transdev Nederland",
        "sector_slug": "transport",
        "fte": 7500,
        "personeelskosten_mln": 300.0,
        "omzet_budget_mln": 1000.0,
        "vacatures": 50,
        "verzuim_pct": 6.5,
        "gem_jaarsalaris": 40000,
        "kritieke_functies": "buschauffeurs, taxichauffeurs",
        "kosten_werving_mln": 0.9,
        "kosten_onvervuld_mln": 2.3,
        "kosten_inhuur_mln": 3.2,
        "kosten_verzuim_mln": 9.9,
        "kosten_burnout_mln": 23.4,
        "kosten_krapte_totaal_mln": 39.8,
        "ai_baten_25_mln": 23.7,
        "ai_baten_50_mln": 47.4,
        "ai_baten_75_mln": 71.1,
        "fte_bespaard_50": 2325,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "Geen specifieke initiatieven gevonden, focus op duurzaamheid en sociale innovatie.",
    },
    {
        "name": "Havenbedrijf Rotterdam",
        "sector_slug": "transport",
        "fte": 1440,
        "personeelskosten_mln": 329.0,
        "omzet_budget_mln": 940.0,
        "vacatures": 47,
        "verzuim_pct": 6.1,
        "gem_jaarsalaris": 62000,
        "kritieke_functies": "IT, techniek, logistiek",
        "kosten_werving_mln": 1.4,
        "kosten_onvervuld_mln": 3.4,
        "kosten_inhuur_mln": 4.7,
        "kosten_verzuim_mln": 2.8,
        "kosten_burnout_mln": 4.5,
        "kosten_krapte_totaal_mln": 16.7,
        "ai_baten_25_mln": 11.1,
        "ai_baten_50_mln": 22.2,
        "ai_baten_75_mln": 33.3,
        "fte_bespaard_50": 446,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "Gebruik van AI voor inspectie van assets (Machine Learning Inspector), ontwikkeling van een digital twin van de haven, en inzet op autonome robots.",
    },
    {
        "name": "Keolis Nederland",
        "sector_slug": "transport",
        "fte": 1100,
        "personeelskosten_mln": 43.7,
        "omzet_budget_mln": 220.0,
        "vacatures": 20,
        "verzuim_pct": 15.0,
        "gem_jaarsalaris": 36384,
        "kritieke_functies": "buschauffeurs, medewerkers service & veiligheid (BOA OV)",
        "kosten_werving_mln": 0.3,
        "kosten_onvervuld_mln": 0.8,
        "kosten_inhuur_mln": 1.2,
        "kosten_verzuim_mln": 3.1,
        "kosten_burnout_mln": 3.4,
        "kosten_krapte_totaal_mln": 8.9,
        "ai_baten_25_mln": 3.3,
        "ai_baten_50_mln": 6.7,
        "ai_baten_75_mln": 10.0,
        "fte_bespaard_50": 341,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "Geen specifieke AI- of robotiseringsinitiatieven gevonden, focus ligt op duurzaamheid en data-analyse.",
    },
    {
        "name": "Rijksrederij",
        "sector_slug": "transport",
        "fte": 200,
        "personeelskosten_mln": 15.0,
        "omzet_budget_mln": 150.0,
        "vacatures": 25,
        "verzuim_pct": 6.9,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "nautisch personeel, technisch personeel, contractmanagers",
        "kosten_werving_mln": 0.7,
        "kosten_onvervuld_mln": 1.6,
        "kosten_inhuur_mln": 1.3,
        "kosten_verzuim_mln": 0.4,
        "kosten_burnout_mln": 0.6,
        "kosten_krapte_totaal_mln": 4.6,
        "ai_baten_25_mln": 1.0,
        "ai_baten_50_mln": 1.9,
        "ai_baten_75_mln": 2.9,
        "fte_bespaard_50": 62,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "Er wordt geëxperimenteerd met autonome vaartuigen en slimme sensoren voor inspecties en monitoring.",
    },
    {
        "name": "Havenbedrijf Amsterdam",
        "sector_slug": "transport",
        "fte": 380,
        "personeelskosten_mln": 22.8,
        "omzet_budget_mln": 198.5,
        "vacatures": 8,
        "verzuim_pct": 6.5,
        "gem_jaarsalaris": 60000,
        "kritieke_functies": "IT, projectmanagement, management",
        "kosten_werving_mln": 0.2,
        "kosten_onvervuld_mln": 0.6,
        "kosten_inhuur_mln": 0.8,
        "kosten_verzuim_mln": 0.8,
        "kosten_burnout_mln": 1.2,
        "kosten_krapte_totaal_mln": 3.5,
        "ai_baten_25_mln": 1.8,
        "ai_baten_50_mln": 3.6,
        "ai_baten_75_mln": 5.4,
        "fte_bespaard_50": 118,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_status": "Havenbedrijf Amsterdam gebruikt een AI-oplossing voor het meten van de diepgang van schepen en is betrokken bij het Roboat-project.",
    },
    # ONDERWIJS (10 orgs)
    {
        "name": "Technische Universiteit Delft",
        "sector_slug": "onderwijs",
        "fte": 7577,
        "personeelskosten_mln": 801.6,
        "omzet_budget_mln": 1027.9,
        "vacatures": 90,
        "verzuim_pct": 4.5,
        "gem_jaarsalaris": 105793,
        "kritieke_functies": "wetenschappelijk personeel, technisch personeel",
        "kosten_werving_mln": 3.8,
        "kosten_onvervuld_mln": 9.3,
        "kosten_inhuur_mln": 15.2,
        "kosten_verzuim_mln": 18.4,
        "kosten_burnout_mln": 23.6,
        "kosten_krapte_totaal_mln": 70.4,
        "ai_baten_25_mln": 46.6,
        "ai_baten_50_mln": 93.3,
        "ai_baten_75_mln": 139.9,
        "fte_bespaard_50": 2197,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "TU Delft heeft een breed AI, Data & Digitalisation initiatief met 7 onderzoeksthema's, diverse AI Labs en het Mondai House of AI.",
    },
    {
        "name": "Universiteit Utrecht",
        "sector_slug": "onderwijs",
        "fte": 8900,
        "personeelskosten_mln": 823.2,
        "omzet_budget_mln": 1156.6,
        "vacatures": 54,
        "verzuim_pct": 5.9,
        "gem_jaarsalaris": 92490,
        "kritieke_functies": "Wetenschappelijk personeel (PhD, Postdoc), IT-specialisten, administratief personeel",
        "kosten_werving_mln": 2.0,
        "kosten_onvervuld_mln": 4.9,
        "kosten_inhuur_mln": 8.0,
        "kosten_verzuim_mln": 24.8,
        "kosten_burnout_mln": 27.8,
        "kosten_krapte_totaal_mln": 67.4,
        "ai_baten_25_mln": 48.2,
        "ai_baten_50_mln": 96.5,
        "ai_baten_75_mln": 144.7,
        "fte_bespaard_50": 2581,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "Diverse AI-onderzoeksgroepen (Human-centered AI, Embodied AI), AI Labs (AI & Media Lab) en een masterprogramma Artificial Intelligence.",
    },
    {
        "name": "Universiteit van Amsterdam",
        "sector_slug": "onderwijs",
        "fte": 9000,
        "personeelskosten_mln": 566.0,
        "omzet_budget_mln": 850.0,
        "vacatures": 25,
        "verzuim_pct": 4.0,
        "gem_jaarsalaris": 79560,
        "kritieke_functies": "Gespecialiseerd wetenschappelijk personeel, IT-specialisten, docenten in kraptesectoren",
        "kosten_werving_mln": 0.8,
        "kosten_onvervuld_mln": 2.0,
        "kosten_inhuur_mln": 3.2,
        "kosten_verzuim_mln": 14.6,
        "kosten_burnout_mln": 28.1,
        "kosten_krapte_totaal_mln": 48.6,
        "ai_baten_25_mln": 38.8,
        "ai_baten_50_mln": 77.7,
        "ai_baten_75_mln": 116.5,
        "fte_bespaard_50": 2610,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "De UvA heeft diverse AI-initiatieven, waaronder het 'Citizens, Society and Artificial Intelligence (CiSAI)' platform en het 'Innovation Center for AI (ICAI)'.",
    },
    {
        "name": "Rijksuniversiteit Groningen",
        "sector_slug": "onderwijs",
        "fte": 7200,
        "personeelskosten_mln": 650.0,
        "omzet_budget_mln": 1000.0,
        "vacatures": 36,
        "verzuim_pct": 5.6,
        "gem_jaarsalaris": 55000,
        "kritieke_functies": "gespecialiseerd academisch personeel, onderzoekers, IT-specialisten",
        "kosten_werving_mln": 0.8,
        "kosten_onvervuld_mln": 1.9,
        "kosten_inhuur_mln": 3.2,
        "kosten_verzuim_mln": 11.3,
        "kosten_burnout_mln": 22.5,
        "kosten_krapte_totaal_mln": 39.7,
        "ai_baten_25_mln": 27.9,
        "ai_baten_50_mln": 55.7,
        "ai_baten_75_mln": 83.6,
        "fte_bespaard_50": 2088,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "De RUG heeft een Interactive Robot Learning Laboratory (IRL-LAB) en biedt een master in AI met focus op cognitieve robotica.",
    },
    {
        "name": "Wageningen University & Research",
        "sector_slug": "onderwijs",
        "fte": 3943,
        "personeelskosten_mln": 354.7,
        "omzet_budget_mln": 494.8,
        "vacatures": 52,
        "verzuim_pct": 4.7,
        "gem_jaarsalaris": 89965,
        "kritieke_functies": "Wetenschappelijk personeel (hoogleraren, universitair (hoofd)docenten, onderzoekers), IT-specialisten",
        "kosten_werving_mln": 1.9,
        "kosten_onvervuld_mln": 4.6,
        "kosten_inhuur_mln": 7.5,
        "kosten_verzuim_mln": 8.5,
        "kosten_burnout_mln": 12.3,
        "kosten_krapte_totaal_mln": 34.8,
        "ai_baten_25_mln": 20.7,
        "ai_baten_50_mln": 41.3,
        "ai_baten_75_mln": 62.0,
        "fte_bespaard_50": 1143,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "WUR has a dedicated AI research group focusing on knowledge engineering, machine learning, deep learning, and their societal implications.",
    },
    {
        "name": "Fontys Hogescholen",
        "sector_slug": "onderwijs",
        "fte": 4278,
        "personeelskosten_mln": 449.7,
        "omzet_budget_mln": 541.8,
        "vacatures": 8,
        "verzuim_pct": 6.0,
        "gem_jaarsalaris": 105115,
        "kritieke_functies": "Technisch personeel, managementfuncties, docenten",
        "kosten_werving_mln": 0.3,
        "kosten_onvervuld_mln": 0.8,
        "kosten_inhuur_mln": 1.3,
        "kosten_verzuim_mln": 13.8,
        "kosten_burnout_mln": 13.3,
        "kosten_krapte_totaal_mln": 29.6,
        "ai_baten_25_mln": 26.4,
        "ai_baten_50_mln": 52.7,
        "ai_baten_75_mln": 79.1,
        "fte_bespaard_50": 1241,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "Fontys heeft een lectoraat AI en Big Data, en een eigen AI-platform in ontwikkeling voor studenten en docenten.",
    },
    {
        "name": "Erasmus Universiteit Rotterdam",
        "sector_slug": "onderwijs",
        "fte": 3959,
        "personeelskosten_mln": 325.1,
        "omzet_budget_mln": 862.5,
        "vacatures": 40,
        "verzuim_pct": 4.0,
        "gem_jaarsalaris": 82117,
        "kritieke_functies": "Academisch personeel, PhD-posities, IT-personeel",
        "kosten_werving_mln": 1.3,
        "kosten_onvervuld_mln": 3.2,
        "kosten_inhuur_mln": 5.3,
        "kosten_verzuim_mln": 6.6,
        "kosten_burnout_mln": 12.4,
        "kosten_krapte_totaal_mln": 28.8,
        "ai_baten_25_mln": 18.9,
        "ai_baten_50_mln": 37.7,
        "ai_baten_75_mln": 56.6,
        "fte_bespaard_50": 1148,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "Erasmus Universiteit heeft het 'Societal Impact of AI' (AiPact) initiatief en een project met een bezorgrobot op de campus.",
    },
    {
        "name": "ROC van Amsterdam-Flevoland",
        "sector_slug": "onderwijs",
        "fte": 3325,
        "personeelskosten_mln": 192.9,
        "omzet_budget_mln": 250.0,
        "vacatures": 32,
        "verzuim_pct": 6.5,
        "gem_jaarsalaris": 58000,
        "kritieke_functies": "Docenten (diverse vakgebieden), IT-specialisten (security, data, beheer), onderwijsondersteunend personeel",
        "kosten_werving_mln": 0.7,
        "kosten_onvervuld_mln": 1.8,
        "kosten_inhuur_mln": 3.0,
        "kosten_verzuim_mln": 6.4,
        "kosten_burnout_mln": 10.4,
        "kosten_krapte_totaal_mln": 22.3,
        "ai_baten_25_mln": 11.3,
        "ai_baten_50_mln": 22.7,
        "ai_baten_75_mln": 34.0,
        "fte_bespaard_50": 964,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "Inzet van 'diplomeringsrobot' voor administratie, AI-trainingen voor docenten en een 'House of Digital' met een AI-community.",
    },
    {
        "name": "Hogeschool Rotterdam",
        "sector_slug": "onderwijs",
        "fte": 3345,
        "personeelskosten_mln": 352.9,
        "omzet_budget_mln": 393.4,
        "vacatures": 30,
        "verzuim_pct": 6.0,
        "gem_jaarsalaris": 60000,
        "kritieke_functies": "Docenten IT, Docenten Techniek, Onderzoekers",
        "kosten_werving_mln": 0.7,
        "kosten_onvervuld_mln": 1.8,
        "kosten_inhuur_mln": 2.9,
        "kosten_verzuim_mln": 6.1,
        "kosten_burnout_mln": 10.4,
        "kosten_krapte_totaal_mln": 21.9,
        "ai_baten_25_mln": 14.6,
        "ai_baten_50_mln": 29.2,
        "ai_baten_75_mln": 43.8,
        "fte_bespaard_50": 970,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "Hogeschool Rotterdam heeft een bachelor Applied Data Science & AI en een master AI Translator. Er zijn interne discussies over de rol van AI in onderwijs.",
    },
    {
        "name": "Hogeschool van Amsterdam",
        "sector_slug": "onderwijs",
        "fte": 3662,
        "personeelskosten_mln": 355.4,
        "omzet_budget_mln": 546.8,
        "vacatures": 16,
        "verzuim_pct": 5.1,
        "gem_jaarsalaris": 62357,
        "kritieke_functies": "docenten, ICT-personeel",
        "kosten_werving_mln": 0.4,
        "kosten_onvervuld_mln": 1.0,
        "kosten_inhuur_mln": 1.6,
        "kosten_verzuim_mln": 5.9,
        "kosten_burnout_mln": 11.4,
        "kosten_krapte_totaal_mln": 20.3,
        "ai_baten_25_mln": 15.7,
        "ai_baten_50_mln": 31.3,
        "ai_baten_75_mln": 47.0,
        "fte_bespaard_50": 1062,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_status": "De HvA heeft een Centre of Expertise Applied AI, een Learning Community 'AI & Publieke Diensten' en een Robotlab.",
    },
]

# Sector profiles data
SECTOR_PROFILES_DATA = [
    {
        "sector_slug": "zorg",
        "fte": 93530,
        "personeelskosten_mln": 7078.3,
        "omzet_budget_mln": 13050.2,
        "vacatures": 1407,
        "gem_verzuim_pct": 6.3,
        "kosten_krapte_mln": 1050.5,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 8,
        "ai_baten_25_mln": 404.5,
        "ai_baten_50_mln": 808.9,
        "ai_baten_75_mln": 1213.4,
        "fte_bespaard_50": 24785,
        "kritieke_functies": "verpleegkundigen, artsen, OK-assistenten",
    },
    {
        "sector_slug": "energie",
        "fte": 52149,
        "personeelskosten_mln": 4239.8,
        "omzet_budget_mln": 389104.0,
        "vacatures": 1117,
        "gem_verzuim_pct": 4.8,
        "kosten_krapte_mln": 494.0,
        "ai_ondersteuning_pct": 20,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 12,
        "ai_baten_25_mln": 265.9,
        "ai_baten_50_mln": 531.8,
        "ai_baten_75_mln": 797.7,
        "fte_bespaard_50": 15645,
        "kritieke_functies": "elektromonteurs, ingenieurs, projectleiders",
    },
    {
        "sector_slug": "overheid",
        "fte": 318624,
        "personeelskosten_mln": 27370.2,
        "omzet_budget_mln": 80003.6,
        "vacatures": 6961,
        "gem_verzuim_pct": 6.5,
        "kosten_krapte_mln": 2891.6,
        "ai_ondersteuning_pct": 30,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 15,
        "ai_baten_25_mln": 1862.4,
        "ai_baten_50_mln": 3724.8,
        "ai_baten_75_mln": 5587.2,
        "fte_bespaard_50": 106739,
        "kritieke_functies": "IT-specialisten, beleidsadviseurs, uitvoerend personeel",
    },
    {
        "sector_slug": "bouw",
        "fte": 64810,
        "personeelskosten_mln": 5471.1,
        "omzet_budget_mln": 31288.3,
        "vacatures": 2683,
        "gem_verzuim_pct": 5.4,
        "kosten_krapte_mln": 863.6,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 22,
        "ai_vervanging_pct": 10,
        "ai_baten_25_mln": 232.6,
        "ai_baten_50_mln": 465.1,
        "ai_baten_75_mln": 697.7,
        "fte_bespaard_50": 16202,
        "kritieke_functies": "bouwarbeiders, machinemonteurs, werkvoorbereiders",
    },
    {
        "sector_slug": "transport",
        "fte": 78126,
        "personeelskosten_mln": 7735.4,
        "omzet_budget_mln": 23830.5,
        "vacatures": 1074,
        "gem_verzuim_pct": 7.7,
        "kosten_krapte_mln": 626.5,
        "ai_ondersteuning_pct": 15,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 22,
        "ai_baten_25_mln": 448.7,
        "ai_baten_50_mln": 897.5,
        "ai_baten_75_mln": 1346.2,
        "fte_bespaard_50": 24219,
        "kritieke_functies": "machinisten, chauffeurs, piloten",
    },
    {
        "sector_slug": "onderwijs",
        "fte": 55189,
        "personeelskosten_mln": 4871.5,
        "omzet_budget_mln": 7123.8,
        "vacatures": 383,
        "gem_verzuim_pct": 5.2,
        "kosten_krapte_mln": 383.9,
        "ai_ondersteuning_pct": 25,
        "ai_augmentatie_pct": 28,
        "ai_vervanging_pct": 5,
        "ai_baten_25_mln": 269.0,
        "ai_baten_50_mln": 538.0,
        "ai_baten_75_mln": 807.0,
        "fte_bespaard_50": 16005,
        "kritieke_functies": "docenten exacte vakken, onderzoekers",
    },
    {
        "sector_slug": "ict",
        "fte": 87420,
        "personeelskosten_mln": 8936.2,
        "omzet_budget_mln": 52680.0,
        "vacatures": 3214,
        "gem_verzuim_pct": 3.8,
        "kosten_krapte_mln": 1285.6,
        "ai_ondersteuning_pct": 28,
        "ai_augmentatie_pct": 25,
        "ai_vervanging_pct": 12,
        "ai_baten_25_mln": 558.5,
        "ai_baten_50_mln": 1117.0,
        "ai_baten_75_mln": 1675.5,
        "fte_bespaard_50": 28445,
        "kritieke_functies": "software developers, cybersecurity specialisten, data engineers",
    },
    {
        "sector_slug": "finance",
        "fte": 72350,
        "personeelskosten_mln": 7891.4,
        "omzet_budget_mln": 98420.0,
        "vacatures": 1856,
        "gem_verzuim_pct": 4.1,
        "kosten_krapte_mln": 742.4,
        "ai_ondersteuning_pct": 22,
        "ai_augmentatie_pct": 20,
        "ai_vervanging_pct": 15,
        "ai_baten_25_mln": 493.2,
        "ai_baten_50_mln": 986.4,
        "ai_baten_75_mln": 1479.6,
        "fte_bespaard_50": 20558,
        "kritieke_functies": "compliance officers, actuarissen, risk managers",
    },
    {
        "sector_slug": "industrie",
        "fte": 118760,
        "personeelskosten_mln": 8932.4,
        "omzet_budget_mln": 74520.0,
        "vacatures": 4127,
        "gem_verzuim_pct": 5.1,
        "kosten_krapte_mln": 1649.3,
        "ai_ondersteuning_pct": 18,
        "ai_augmentatie_pct": 15,
        "ai_vervanging_pct": 8,
        "ai_baten_25_mln": 357.3,
        "ai_baten_50_mln": 714.6,
        "ai_baten_75_mln": 1071.9,
        "fte_bespaard_50": 24339,
        "kritieke_functies": "CNC-operators, onderhoudstechnici, procesoperators",
    },
]


async def run_migration():
    """Run the organization data migration SQL."""
    migration_file = Path(__file__).parent.parent.parent / "migrations" / "004_organization_data.sql"

    # Check if sector_profiles table already exists
    exists = await fetch_one(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sector_profiles')"
    )
    if exists and exists.get("exists"):
        logger.info("organization_data_tables_exist", status="skipping migration")
        return

    logger.info("organization_data_running_migration")
    sql = migration_file.read_text()

    # Execute each statement separately (asyncpg doesn't support multi-statement)
    async with get_connection() as conn:
        statements = [s.strip() for s in sql.split(';') if s.strip() and not s.strip().startswith('--')]

        for stmt in statements:
            try:
                await conn.execute(stmt)
            except Exception as e:
                # Skip errors for IF NOT EXISTS statements
                if 'already exists' in str(e).lower():
                    continue
                logger.warning("migration_statement_error", error=str(e), stmt=stmt[:100])

    logger.info("organization_data_migration_complete")


async def seed_organizations():
    """Seed organization data from the readiness scan into the database."""

    # Check if data already loaded
    count = await fetch_one("SELECT COUNT(*) as cnt FROM organizations WHERE source = 'readiness_scan_2026'")
    if count and count.get("cnt", 0) > 0:
        logger.info("organization_data_already_seeded", count=count["cnt"])
        return

    logger.info("seeding_organization_data", organizations=len(ORGANIZATIONS_DATA))

    async with get_connection() as conn:
        # Prepare insert statements for organizations
        for org in ORGANIZATIONS_DATA:
            stmt = """
            INSERT INTO organizations (
                name, sector_slug, employee_count,
                personeelskosten_mln, omzet_budget_mln, vacatures, verzuim_pct, gem_jaarsalaris,
                kritieke_functies, kosten_krapte_totaal_mln,
                kosten_werving_mln, kosten_onvervuld_mln, kosten_inhuur_mln,
                kosten_verzuim_mln, kosten_burnout_mln,
                ai_baten_25_mln, ai_baten_50_mln, ai_baten_75_mln,
                fte_bespaard_50,
                ai_ondersteuning_pct, ai_augmentatie_pct, ai_vervanging_pct,
                ai_status, source, is_public_benchmark
            )
            VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
                $11, $12, $13, $14, $15, $16, $17, $18, $19,
                $20, $21, $22, $23, $24, $25
            )
            """

            values = (
                org["name"],
                org["sector_slug"],
                org["fte"],
                org.get("personeelskosten_mln"),
                org.get("omzet_budget_mln"),
                org.get("vacatures"),
                org.get("verzuim_pct"),
                org.get("gem_jaarsalaris"),
                org.get("kritieke_functies"),
                org.get("kosten_krapte_totaal_mln"),
                org.get("kosten_werving_mln"),
                org.get("kosten_onvervuld_mln"),
                org.get("kosten_inhuur_mln"),
                org.get("kosten_verzuim_mln"),
                org.get("kosten_burnout_mln"),
                org.get("ai_baten_25_mln"),
                org.get("ai_baten_50_mln"),
                org.get("ai_baten_75_mln"),
                org.get("fte_bespaard_50"),
                org.get("ai_ondersteuning_pct"),
                org.get("ai_augmentatie_pct"),
                org.get("ai_vervanging_pct"),
                org.get("ai_status"),
                "readiness_scan_2026",
                True
            )

            try:
                await conn.execute(stmt, *values)
            except Exception as e:
                logger.warning("organization_insert_error", org=org["name"], error=str(e))

    logger.info("organization_data_seeding_complete")


async def seed_sector_profiles():
    """Seed sector profile aggregates into the database."""

    # Check if data already loaded
    count = await fetch_one("SELECT COUNT(*) as cnt FROM sector_profiles")
    if count and count.get("cnt", 0) >= 9:
        logger.info("sector_profiles_already_seeded", count=count["cnt"])
        return

    # Clear old data if partial (less than 9 sectors)
    if count and count.get("cnt", 0) > 0:
        logger.info("sector_profiles_partial_seed", count=count["cnt"], action="reseed")
        await execute("DELETE FROM sector_profiles")

    logger.info("seeding_sector_profiles", sectors=len(SECTOR_PROFILES_DATA))

    async with get_connection() as conn:
        for sector in SECTOR_PROFILES_DATA:
            stmt = """
            INSERT INTO sector_profiles (
                sector_slug, fte, personeelskosten_mln, omzet_budget_mln,
                vacatures, gem_verzuim_pct, kosten_krapte_mln,
                ai_ondersteuning_pct, ai_augmentatie_pct, ai_vervanging_pct,
                ai_baten_25_mln, ai_baten_50_mln, ai_baten_75_mln,
                fte_bespaard_50, kritieke_functies
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
            ON CONFLICT (sector_slug) DO UPDATE SET
                fte = EXCLUDED.fte,
                personeelskosten_mln = EXCLUDED.personeelskosten_mln,
                omzet_budget_mln = EXCLUDED.omzet_budget_mln,
                vacatures = EXCLUDED.vacatures,
                gem_verzuim_pct = EXCLUDED.gem_verzuim_pct,
                kosten_krapte_mln = EXCLUDED.kosten_krapte_mln,
                ai_ondersteuning_pct = EXCLUDED.ai_ondersteuning_pct,
                ai_augmentatie_pct = EXCLUDED.ai_augmentatie_pct,
                ai_vervanging_pct = EXCLUDED.ai_vervanging_pct,
                ai_baten_25_mln = EXCLUDED.ai_baten_25_mln,
                ai_baten_50_mln = EXCLUDED.ai_baten_50_mln,
                ai_baten_75_mln = EXCLUDED.ai_baten_75_mln,
                fte_bespaard_50 = EXCLUDED.fte_bespaard_50,
                kritieke_functies = EXCLUDED.kritieke_functies,
                updated_at = CURRENT_TIMESTAMP
            """

            values = (
                sector["sector_slug"],
                sector["fte"],
                sector.get("personeelskosten_mln"),
                sector.get("omzet_budget_mln"),
                sector.get("vacatures"),
                sector.get("gem_verzuim_pct"),
                sector.get("kosten_krapte_mln"),
                sector.get("ai_ondersteuning_pct"),
                sector.get("ai_augmentatie_pct"),
                sector.get("ai_vervanging_pct"),
                sector.get("ai_baten_25_mln"),
                sector.get("ai_baten_50_mln"),
                sector.get("ai_baten_75_mln"),
                sector.get("fte_bespaard_50"),
                sector.get("kritieke_functies"),
            )

            try:
                await conn.execute(stmt, *values)
            except Exception as e:
                logger.warning("sector_profile_insert_error", sector=sector["sector_slug"], error=str(e))

    logger.info("sector_profiles_seeding_complete")


async def seed_organization_data():
    """Main function to seed all organization data."""
    await run_migration()
    await seed_organizations()
    await seed_sector_profiles()
    logger.info("organization_data_seed_complete")
